version: '3.4'

services:
  productmain:
    image: productmain
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
